version: "3.7"

services:
  cypress:
    image: kudoshunsuke/docker-cypress
    build:
      context: ./
      dockerfile: ./Dockerfile
      #args:
      #  http_proxy: ${http_proxy}
      #  https_proxy: ${http_proxy}
      #  no_proxy: ${no_proxy}
    #environment:
    volumes:
      - ./cypress:/home/node/cypress
      - ./entrypoint.sh:/entrypoint.sh
    #ports:
    entrypoint: /entrypoint.sh
    tty: true
    command: bash -c "cypress run -s cypress/integration/prod/login.spec.js"
    #command: bash
    working_dir: /home/node
    #logging:
    #  driver: "json-file" # defaults if not specified
    #  options:
    #    max-size: "1m"
    #    max-file: "1"
